const users = [
    {
      userId: '1a2b3c',
      first_name: 'John',
      last_name: 'Doe',
      position: 'Software Engineer',
      experience: 5,
      current_company: 'Microsoft',
      bio: 'Passionate about technology and innovation',
      dob: '1990-01-01',
      email: 'johndoe@gmail.com',
      phone_number: '9876543210',
      password: 'password123',
      image: 'john.png',
      description: 'Specialist in Cloud Computing',
      rating: 4.8,
      location: 'Bangalore',
      callPrice: '₹500/hr',
      chatPrice: '₹250/hr',
      videoPrice: '₹700/hr',
      review: [
        {
          userid: 'abc123',
          comment: 'Very knowledgeable!',
          rating: 5,
          datetime: '2024-01-01',
        },
      ],
    },
    {
      userId: '4d5e6f',
      first_name: 'Jane',
      last_name: 'Smith',
      position: 'Data Scientist',
      experience: 7,
      current_company: 'Amazon',
      bio: 'Data enthusiast with a knack for insights',
      dob: '1992-02-15',
      email: 'janesmith@gmail.com',
      phone_number: '9123456780',
      password: 'datascience',
      image: 'jane.png',
      description: 'Expert in Machine Learning',
      rating: 4.9,
      location: 'Hyderabad',
      callPrice: '₹600/hr',
      chatPrice: '₹300/hr',
      videoPrice: '₹800/hr',
      review: [
        {
          userid: 'def456',
          comment: 'Insightful and clear explanations.',
          rating: 5,
          datetime: '2024-02-15',
        },
      ],
    },
    {
      userId: '7g8h9i',
      first_name: 'Alice',
      last_name: 'Johnson',
      position: 'UX Designer',
      experience: 6,
      current_company: 'Facebook',
      bio: 'Designs that speak',
      dob: '1988-03-10',
      email: 'alicejohnson@gmail.com',
      phone_number: '8765432109',
      password: 'designlover',
      image: 'alice.png',
      description: 'Expert in User Experience Design',
      rating: 4.6,
      location: 'Mumbai',
      callPrice: '₹450/hr',
      chatPrice: '₹220/hr',
      videoPrice: '₹650/hr',
      review: [
        {
          userid: 'ghi789',
          comment: 'Creative and professional.',
          rating: 4,
          datetime: '2024-03-10',
        },
      ],
    },
    {
      userId: 'j1k2l3',
      first_name: 'Bob',
      last_name: 'Brown',
      position: 'Product Manager',
      experience: 8,
      current_company: 'Apple',
      bio: 'Bridging the gap between users and developers',
      dob: '1985-04-20',
      email: 'bobbrown@gmail.com',
      phone_number: '8234567890',
      password: 'productguru',
      image: 'bob.png',
      description: 'Expert in Product Strategy',
      rating: 4.5,
      location: 'Delhi',
      callPrice: '₹550/hr',
      chatPrice: '₹275/hr',
      videoPrice: '₹750/hr',
      review: [
        {
          userid: 'jkl012',
          comment: 'Great strategic insights.',
          rating: 4.5,
          datetime: '2024-04-20',
        },
      ],
    },
    {
      userId: 'm4n5o6',
      first_name: 'Charlie',
      last_name: 'Davis',
      position: 'Full Stack Developer',
      experience: 4,
      current_company: 'Netflix',
      bio: 'Building seamless digital experiences',
      dob: '1994-05-25',
      email: 'charliedavis@gmail.com',
      phone_number: '8987654321',
      password: 'fullstackdev',
      image: 'charlie.png',
      description: 'Expert in Web Development',
      rating: 4.7,
      location: 'Pune',
      callPrice: '₹400/hr',
      chatPrice: '₹200/hr',
      videoPrice: '₹600/hr',
      review: [
        {
          userid: 'mno345',
          comment: 'Efficient and detail-oriented.',
          rating: 4.7,
          datetime: '2024-05-25',
        },
      ],
    },
    {
      userId: 'p7q8r9',
      first_name: 'Eve',
      last_name: 'Clark',
      position: 'DevOps Engineer',
      experience: 9,
      current_company: 'Spotify',
      bio: 'Ensuring smooth and efficient operations',
      dob: '1987-06-15',
      email: 'eveclark@gmail.com',
      phone_number: '8123456789',
      password: 'opsmaster',
      image: 'eve.png',
      description: 'Expert in Continuous Integration',
      rating: 4.8,
      location: 'Chennai',
      callPrice: '₹500/hr',
      chatPrice: '₹250/hr',
      videoPrice: '₹700/hr',
      review: [
        {
          userid: 'pqr678',
          comment: 'Reliable and always available.',
          rating: 4.8,
          datetime: '2024-06-15',
        },
      ],
    },
    {
      userId: 's1t2u3',
      first_name: 'Frank',
      last_name: 'Evans',
      position: 'AI Researcher',
      experience: 10,
      current_company: 'Tesla',
      bio: 'Exploring the frontiers of AI',
      dob: '1983-07-07',
      email: 'frankevans@gmail.com',
      phone_number: '8567890123',
      password: 'aiinnovator',
      image: 'frank.png',
      description: 'Expert in Artificial Intelligence',
      rating: 4.9,
      location: 'Kolkata',
      callPrice: '₹700/hr',
      chatPrice: '₹350/hr',
      videoPrice: '₹900/hr',
      review: [
        {
          userid: 'stu901',
          comment: 'Cutting-edge knowledge.',
          rating: 5,
          datetime: '2024-07-07',
        },
      ],
    },
    {
      userId: 'v4w5x6',
      first_name: 'Grace',
      last_name: 'Miller',
      position: 'Cybersecurity Analyst',
      experience: 6,
      current_company: 'IBM',
      bio: 'Protecting data with precision',
      dob: '1991-08-12',
      email: 'gracemiller@gmail.com',
      phone_number: '8654321098',
      password: 'secure123',
      image: 'grace.png',
      description: 'Expert in Cybersecurity',
      rating: 4.6,
      location: 'Ahmedabad',
      callPrice: '₹550/hr',
      chatPrice: '₹275/hr',
      videoPrice: '₹750/hr',
      review: [
        {
          userid: 'vwx234',
          comment: 'Highly skilled in security protocols.',
          rating: 4.5,
          datetime: '2024-08-12',
        },
      ],
    },
    {
      userId: 'y7z8a9',
      first_name: 'Henry',
      last_name: 'Moore',
      position: 'Blockchain Developer',
      experience: 3,
      current_company: 'Coinbase',
      bio: 'Building the future of finance',
      dob: '1995-09-30',
      email: 'henrymoore@gmail.com',
      phone_number: '8123678945',
      password: 'blockchainwizard',
      image: 'henry.png',
      description: 'Expert in Blockchain Technology',
      rating: 4.7,
      location: 'Noida',
      callPrice: '₹450/hr',
      chatPrice: '₹225/hr',
      videoPrice: '₹650/hr',
      review: [
        {
          userid: 'yzb567',
          comment: 'Innovative and forward-thinking.',
          rating: 4.6,
          datetime: '2024-09-30',
        },
      ],
    },
    {
      userId: 'b1c2d3',
      first_name: 'Ivy',
      last_name: 'Taylor',
      position: 'Mobile App Developer',
      experience: 5,
      current_company: 'Snapchat',
      bio: 'Crafting intuitive mobile experiences',
      dob: '1993-10-05',
      email: 'ivytaylor@gmail.com',
      phone_number: '7890654321',
      password: 'mobileexpert',
      image: 'ivy.png',
      description: 'Expert in Mobile App Development',
      rating: 4.8,
      location: 'Gurgaon',
      callPrice: '₹400/hr',
      chatPrice: '₹200/hr',
      videoPrice: '₹600/hr',
      review: [
        {
          userid: 'bcd890',
          comment: 'User-friendly designs.',
          rating: 4.7,
          datetime: '2024-10-05',
        },
      ],
    },
  ];
  